### ISSUE TITLE
Make 'Nutrition Facts' label

### ISSUE THREAD

**Issue by dwblair** [p-v-o-s/riffle-ito#2]
![rifflelabel](https://cloud.githubusercontent.com/assets/639760/3027999/30445cfa-e028-11e3-8816-b8fbdc38216b.png)

**Comment by BobStevens** [comment]
perhaps a vintage beverage logo...
![riffle](https://cloud.githubusercontent.com/assets/4740637/3029463/75da4e70-e035-11e3-9c63-8aa23d116dfc.png)
![riffle2](https://cloud.githubusercontent.com/assets/4740637/3032722/72b22f80-e05b-11e3-9458-ed36393352e9.png)

**Comment by dwblair** [comment]
Bob.  You're a genius.  MAJORLY AWESOME.

**Comment by kanarinka** [comment]
![rifflelabel2](https://cloud.githubusercontent.com/assets/1102550/3116949/32e98ee2-e723-11e3-82cc-9f281cf4ee9f.png)
Another label idea!! Let's keep iterating and then we can make a couple and do market research on which label seduces the most citizen scientists :+1:

**Comment by kanarinka** [comment]
![rifflelabel3](https://cloud.githubusercontent.com/assets/1102550/3117523/aab2b39e-e72e-11e3-8b7b-fed8c4b8d51d.png)
And here's one using Bob's font which I like a great deal!

**Comment by kanarinka** [comment]
![rifflelabel4](https://cloud.githubusercontent.com/assets/1102550/3117865/ece08718-e734-11e3-8b70-3ab5bd1f3163.png)
What about this for the water bottle conference stickers?? I'd have to redo it more carefully and not sure if the bleed would work but let me know

**Comment by BobStevens** [comment]
Nice, the font I used is an open font called Lemon by Eduardo Tunni.

**Comment by kanarinka** [comment]
❤️❤️❤️😄

El miércoles, 18 de marzo de 2015, dwblair notifications@github.com
escribió:

> Closed #2 https://github.com/p-v-o-s/riffle-ito/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/p-v-o-s/riffle-ito/issues/2#event-258748090.

## 

---

www.kanarinka.com    ||    kanarinka@ikatun.org    ||    617-501-2441

---
